### PR TITLE
fix (provider/bedrock): update amazon bedrock package to use safe version of aws sdk

### PR DESCRIPTION
**Pull request by MrHertal**
In `amazon-bedrock` package, current version of `@aws-sdk/client-bedrock-runtime` is locked.

Which leads to vulnerability alerts on project that installs `@ai-sdk/amazon-bedrock`.

I run `npm audit` on such project and get:

```bash
# npm audit report

fast-xml-parser  <4.4.1
Severity: high
fast-xml-parser vulnerable to ReDOS at currency parsing - https://github.com/advisories/GHSA-mpg4-rc92-vx8v
No fix available
node_modules/@ai-sdk/amazon-bedrock/node_modules/fast-xml-parser
  @aws-sdk/core  3.529.1 - 3.620.1
  Depends on vulnerable versions of fast-xml-parser
  node_modules/@ai-sdk/amazon-bedrock/node_modules/@aws-sdk/core
    @aws-sdk/client-bedrock-runtime  3.529.1 - 3.620.1
    Depends on vulnerable versions of @aws-sdk/client-sso-oidc
    Depends on vulnerable versions of @aws-sdk/client-sts
    Depends on vulnerable versions of @aws-sdk/core
    Depends on vulnerable versions of @aws-sdk/credential-provider-node
    node_modules/@ai-sdk/amazon-bedrock/node_modules/@aws-sdk/client-bedrock-runtime
      @ai-sdk/amazon-bedrock  *
      Depends on vulnerable versions of @aws-sdk/client-bedrock-runtime
      node_modules/@ai-sdk/amazon-bedrock
    @aws-sdk/client-sso  3.529.1 - 3.620.1
    Depends on vulnerable versions of @aws-sdk/core
    node_modules/@ai-sdk/amazon-bedrock/node_modules/@aws-sdk/client-sso
      @aws-sdk/credential-provider-sso  3.529.1 - 3.620.1
      Depends on vulnerable versions of @aws-sdk/client-sso
      node_modules/@ai-sdk/amazon-bedrock/node_modules/@aws-sdk/credential-provider-sso
        @aws-sdk/credential-provider-ini  3.529.1 - 3.620.1
        Depends on vulnerable versions of @aws-sdk/credential-provider-sso
        node_modules/@ai-sdk/amazon-bedrock/node_modules/@aws-sdk/credential-provider-ini
        @aws-sdk/credential-provider-node  3.529.1 - 3.620.1
        Depends on vulnerable versions of @aws-sdk/credential-provider-ini
        Depends on vulnerable versions of @aws-sdk/credential-provider-sso
        node_modules/@ai-sdk/amazon-bedrock/node_modules/@aws-sdk/credential-provider-node
          @aws-sdk/client-sso-oidc  3.529.1 - 3.620.1
          Depends on vulnerable versions of @aws-sdk/client-sts
          Depends on vulnerable versions of @aws-sdk/core
          Depends on vulnerable versions of @aws-sdk/credential-provider-node
          node_modules/@ai-sdk/amazon-bedrock/node_modules/@aws-sdk/client-sso-oidc
            @aws-sdk/client-sts  3.529.1 - 3.620.1
            Depends on vulnerable versions of @aws-sdk/client-sso-oidc
            Depends on vulnerable versions of @aws-sdk/core
            Depends on vulnerable versions of @aws-sdk/credential-provider-node
            node_modules/@ai-sdk/amazon-bedrock/node_modules/@aws-sdk/client-sts

10 high severity vulnerabilities

To address issues that do not require attention, run:
  npm audit fix

Some issues need review, and may require choosing
a different dependency.
```

### CODE REVIEW

**Comment by MrHertal** [comment]
In the meantime, I use npm [override](https://docs.npmjs.com/cli/v9/configuring-npm/package-json#overrides) to update the version of `@aws-sdk/client-bedrock-runtime` used by the package:

in `package.json`
```
  "overrides": {
    "@ai-sdk/amazon-bedrock": {
      "@aws-sdk/client-bedrock-runtime": "3.663.0"
    }
  }
```

this removes the vulnerabilities

**Comment by lgrammel** [comment]
can you add a changeset by running `pnpm changeset` in the project root? it should be a patch change for the bedrock provider with the format "fix (provider/bedrock): update amazon bedrock package to use safe version of aws sdk"

**Comment by lgrammel** [comment]
Also, type checks are failing, see `pnpm type-check`. Most likely related to smithy

**Comment by MrHertal** [comment]
@lgrammel done

**Review by lgrammel — APPROVED** [review]

**Pull request merged**
