### PR TITLE
feat(cohere): support AsyncIterable for Cohere

### PR DESCRIPTION
**Pull request by knajjars**
This PR aims to add support for the AsyncIterable in the CohereStream, which is compatible with the response of `co.chatStream` using the official [Cohere SDK](https://github.com/cohere-ai/cohere-typescript). There is [another PR](https://github.com/vercel/ai/pull/870) were we update the Cohere Next.js example as well as the guide.

### CODE REVIEW

**Comment by lgrammel** [comment]
Thanks for the PR! Looks good, the only thing would be adding test cases to `cohere-stream.test.ts`.  You can find examples for tests that use provider SDKs in e.g. `anthropic-stream.test.ts`

**Review by lgrammel — CHANGES_REQUESTED** [review]
Thanks for the PR! Looks good, the only thing would be adding test cases to cohere-stream.test.ts. You can find examples for tests that use provider SDKs in e.g. anthropic-stream.test.ts

**Review by lgrammel — APPROVED** [review]
looks good!

**Comment by knajjars** [comment]
> One thing to add would be documentation.

@igrammel we added documentation in the follow up PR

https://github.com/vercel/ai/pull/870

**Comment by knajjars** [comment]
Hello Vercel team, how can we move forward getting this merged?

**Comment by lgrammel** [comment]
@MaxLeiter this looks good to me - what do you think?

**Comment by tomtobac** [comment]
> @MaxLeiter this looks good to me - what do you think?

Also, could we merge https://github.com/vercel/ai/pull/870 after this one? 🙏

**Comment by tomtobac** [comment]
hey @MaxLeiter @lgrammel any update on this? 🙏

**Review by MaxLeiter — APPROVED** [review]
Thanks!

**Pull request merged**
