### PR TITLE
fix (docs): updating rag to match latest code to guide

### PR DESCRIPTION
**Pull request by dorelljames**
As I followed through the guide, the latest code didn't matched the docs. This updates it to match it properly.

### Latest Code
image

### Latest in the [docs](https://sdk.vercel.ai/docs/guides/rag-chatbot#update-server-action)
CleanShot 2024-10-24 at 10 30 24@2x

### CODE REVIEW

**Comment by lgrammel** [comment]
Thank you! Can you run `pnpm prettier-fix` in the repository?

**Comment by lgrammel** [comment]
@nicoalbanese does this look good?

**Comment by nicoalbanese** [comment]
hey @dorelljames - great spot! I would actually prefer to keep the code the way it is written in the guide rather than the starter repo. I've updated the starter repo to fix. Thanks again for flagging!

**Comment by dorelljames** [comment]
Anytime @nicoalbanese. 😊

**Pull request closed without merging**
