### PR TITLE
feat(typesafety): added type safe on function call

### PR DESCRIPTION
**Pull request by IdoPesok**
Added type safety to `onFunctionCall`. Uses the initially defined zod schema

Screen Shot 2024-03-01 at 3 36 49 PM

### CODE REVIEW

**Comment by jaredpalmer** [comment]
lgtm but will defer to @lgrammel

**Comment by arnenoori** [comment]
great stuff!

**Review by lgrammel — APPROVED** [review]
Great stuff! I have some ongoing work in that direction as well that is potentially conflicting, but since this is limited to the example, happy to merge (and good inspiration!)

**Comment by lgrammel** [comment]
@IdoPesok can you resolve the typescript quality issues? (main seems to be stable now so it might be a matter of rebasing/merging main into this branch)

**Comment by IdoPesok** [comment]
The TS quality issue was on me, it was giving this error in the GH action.

Screen Shot 2024-03-02 at 10 30 55 AM

Should be fixed now, strangely `pnpm run type-check` has been giving me 21/21 success on local.

**Comment by lgrammel** [comment]
@IdoPesok awesome. This is great for a single tool. Can you share an example of how it works with two tools (since `onFunctionCall` is a single function)?

**Pull request merged**
