### PR TITLE
fix: deep objects not updating in solid

### LINKED ISSUE #3797: Tool results no longer being streamed to client in v4
### Description

1. Set up a streaming AI agent using SolidStart
2. Have the agent invoke a tool.
3. Observe as no tool results are streamed in

### Code example

My repository is here: https://github.com/spirit-led-software/theaistudybible

See:
1. apps/www/src/server/api/secure/chat.ts for the api
2. apps/www/src/hooks/use-chat.ts for the client

### AI provider

@ai-sdk/solid 1.0.1

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by ian-pascoe**
Resolves: https://github.com/vercel/ai/issues/3797

### CODE REVIEW

**Comment by ian-pascoe** [comment]
@ryansolid - Could you take a look here as well and make sure I am not missing something

**Comment by lgrammel** [comment]
@ian-pascoe are you planning to make further improvements or can i take a look / continue the pr?

**Comment by ian-pascoe** [comment]
@lgrammel - I believe that is all the changes I will make

**Comment by ian-pascoe** [comment]
@lgrammel - I am done making changes. The only thing not included is a use-assistant example

**Comment by lgrammel** [comment]
makes sense, I hope to replace useAssistant with useChat eventually

**Pull request closed without merging**
