### PR TITLE
documentation: Fix-documentation-sentence

### PR DESCRIPTION
**Pull request by untilhamza**
## What this PR does:
Changes the sentence "Set up a stream that of integers" to "Set up a stream of integers" which is more clear.

### CODE REVIEW

**Review by StephanieLeeeee — APPROVED** [review]

**Comment by untilhamza** [comment]
@lgrammel could we please get this one merged 🙏🏼

**Review by lgrammel — APPROVED** [review]
LGTM

**Comment by lgrammel** [comment]
CC @MaxLeiter

**Comment by MaxLeiter** [comment]
thanks!

**Pull request merged**
