### PR TITLE
Add remix example

### PR DESCRIPTION
**Pull request by laiso**
This PR is a revision of #593
I've confirmed that workflows pass in [my forked repo](https://github.com/laiso/ai/actions/runs/8552288522).

### CODE REVIEW

**Comment by broisnischal** [comment]
! update

**Comment by wong2** [comment]
Would you update it with AI SDK 3.1?

**Comment by lilouartz** [comment]
Looks like it is supposed to be something like this:

```ts
import { createOpenAI } from '@ai-sdk/openai';
import { config } from '#app/config.server';
import { defineAction } from '#app/unstable';
import { StreamingTextResponse, streamText } from 'ai';

export default defineAction(async ({ request }) => {
  const openai = createOpenAI({
    apiKey: config.OPENAI_API_KEY,
    compatibility: 'strict',
  });

  const model = openai('gpt-4o');

  const { messages } = await request.json();

  const response = await streamText({
    messages,
    model,
  });

  return new StreamingTextResponse(response.textStream);
});

```

**Comment by lgrammel** [comment]
Would love an React Router / Remix example for the current version of the SDK. This is unfortunately outdated.

**Pull request closed without merging**
