### PR TITLE
fix (ai/ui): parse null as NaN in finish message stream parts

### PR DESCRIPTION
**Pull request by lgrammel**
Continuation of #2486

### CODE REVIEW

**Review by jeremyphilemon — APPROVED** [review]

**Comment by rohitspujari** [comment]
Can you share the timeline of when this make it into a release? Or there is a link to a patch that I can download?

**Comment by lgrammel** [comment]
@rohitspujari it's been released

**Comment by rohitspujari** [comment]
Using "ai": "^3.2.41" now - still doesn't seem to be working. Am I missing something? Every onFinish call looks like this
image

**Comment by BrianHung** [comment]
@rohitspujari The issue depends on whether your model provider includes token usage. What model provider and config are you using?

**Comment by rohitspujari** [comment]
gpt-4-turbo with streamText

**Comment by BrianHung** [comment]
@rohitspujari Set compatibility to strict e.g.

```js
const openai = createOpenAI({ apiKey, baseURL, compatibility: 'strict' });
```

**Comment by rohitspujari** [comment]
@BrianHung It's still returning NaNs. Here is my setup 

`const openaiModel = createOpenAI({
    apiKey: process.env.OPENAI_API_KEY,
    compatibility: 'strict',
  });`

`const result = await streamText({
    system: 'You are a helpful assistant. ',
    model: openaiModel('gpt-4-turbo'),
    tools: tools,
  });`

**Comment by BrianHung** [comment]
Double check `@ai-sdk/openai` is also up-to-date. If that doesn't work, try having a custom as an option into `createOpenAI` and try logging if the results include usage directly from OpenAI.

**Comment by lgrammel** [comment]
@rohitspujari have you updated all ai sdk libraries, including the `@ai-sdk/*` libraries, to their latest patch versions?

**Pull request merged**
