### PR TITLE
fix (ui/svelte): send data to server

### PR DESCRIPTION
**Pull request by lgrammel**

### CODE REVIEW

**Comment by dalton5** [comment]
Hi. When will it be fixed please? Thanks

**Comment by lgrammel** [comment]
@dalton5 this has already been merged and shipped

**Comment by dalton5** [comment]
I still have the error where data is not sent in the body.

I am with sveltekit

` <form
    on:submit={(e) => {
      handleSubmit(e, { data: { model: selectedModel } });
      tick;
      scrollToBottom();
    }}
  >`

And in my server:

`export const POST = (async ({ request }) => {
  const val= await request.json();`

I only have messages in val. I should also have data. Related to this issue: https://github.com/vercel/ai/issues/1270

In my package.json: "ai": "^3.2.5",

**Comment by ghoshsanjoy78** [comment]
I am still having this issue as well. Any fix

**Pull request merged**
