### PR TITLE
add vue assistant composable

### PR DESCRIPTION
**Pull request by dosstx**

### CODE REVIEW

**Comment by lgrammel** [comment]
@dosstx can you add an example to `examples/nuxt-openai`? you can follow `examples/next-openai/app/assistant` and `examples/next-openai/app/api/assistant` (please follow as closely as possible)

**Comment by dosstx** [comment]
@lgrammel Embarrassed to ask, but first time doing this:

I forked and then cloned the `ai` sdk and then added the `useAssistant.ts` file to the `Vue` folder. Then, I ran `pnpm link ai` to link that to my local computer for testing. I tried to then import the `useAssistant` hook to my local Vue app, but I can not find it in the linked `ai` folder. Was there another file I needed to update so I can import the `useAssistant` file into my local Vue app?

**Comment by lgrammel** [comment]
@dosstx if you add to the examples in the repo, it is easier:

Initiially:
1. clone the repo
2. run `pnpm i` in the repo root
3. run `pnpm build` in the repo root

After you made your changes to `packages/core`:
4. go into `packages/core`, run `pnpm build` in there

In a separate terminal tab:
5. go into `examples/nuxt-openai` (in this case)
6. add files, run the example & check it out

The example (inside the repo) will pick up the changes from the `packages/core` build

**Comment by dosstx** [comment]
I was able to get it to work, but I had to simplify it for now so it only uses file search. When I get more time, I'll try to update this merge request with code to more accurately follow the Next example with the home automation functions.

**Pull request closed without merging**
