### PR TITLE
Docs update for Portkey

### PR DESCRIPTION
**Pull request by narengogi**

### CODE REVIEW

**Comment by lgrammel** [comment]
Please keep the standardized provider docs structure.

**Comment by narengogi** [comment]
Hey @lgrammel Just updated docs for portkey community provider. Would be great, if you can review and merge this.

**Review by lgrammel — CHANGES_REQUESTED** [review]
Our provider pages follow a standardized structure for consistency. Check out e.g. the [OpenAI provider](https://sdk.vercel.ai/providers/ai-sdk-providers/openai) for an example.

Please keep the standardized provider docs structure.

**Comment by narengogi** [comment]
> Please keep the standardized provider docs structure.

Sure, thanks!

**Pull request closed without merging**
