### PR TITLE
Feat (#2040): Enable `useAssistant` support in Vue Library

### PR DESCRIPTION
**Pull request by Kunoacc**
# Add Vue Composable for useAssistant

This PR introduces a Vue composable for the `useAssistant` hook, along with testing, some refactoring, examples and documentation updates. It closes out #2040 

## Changes

- **New Feature**: Implemented `useAssistant` as a Vue composable
- **Testing**: Added unit tests for the `useAssistant` composable
- **Refactoring**: Moved all test components to a `test/components` folder for better organization
- **Documentation**: Updated README.md with new information
- **Examples**: Added usage examples for the `useAssistant` Vue composable

## Testing

All new features have been thoroughly tested. To run the tests: `pnpm run test`

## Documentation

The README has been updated with information about the new Vue composable. Additional examples can be found in the `examples` directory.

## Feedback

Any feedback or suggestions for improvement are welcome!

### CODE REVIEW

**Comment by Kunoacc** [comment]
@danielroe if you could take a look, I'd really appreciate it!

cc: @lgrammel 

Have a great week/weekend too!

**Comment by lgrammel** [comment]
Love this PR! My main challenge with Vue right now is that the example is out of date. Would you mind looking into updating the vue example to the latest vue version etc (here or in a separate PR)? That would make it much easier for me to review & accept PRs for Vue.

**Comment by Kunoacc** [comment]
@lgrammel thanks! Are you referring specifically to the example for `useAssistant`? Or samples for the other composables/hooks?

**Comment by lgrammel** [comment]
@Kunoacc the overall `examples/nuxt-openai` is out of date (package versions, examples, etc)

**Comment by dosstx** [comment]
@lgrammel I can try and assist with this.

**Comment by lgrammel** [comment]
The vue/nuxt examples have been updated - @Kunoacc any chance this PR could get a refresh?

**Comment by Kunoacc** [comment]
@lgrammel PR refreshed!

**Comment by lgrammel** [comment]
@Kunoacc awesome!

1. can you revert the refactoring (moving the components)? I prefer to have everything in the same foler
2. we had a change that added a `setThreadId` helper in the meantime: https://github.com/vercel/ai/pull/2209 - could you add it to this PR as well?

**Comment by Kunoacc** [comment]
@lgrammel, updates done

**Pull request closed without merging**
