### PR TITLE
Revert #1065

### PR DESCRIPTION
**Pull request by MaxLeiter**
```
Error calling experimental_onToolCall: [Error: Invalid function call arguments in message. [
  {
    "code": "invalid_type",
    "expected": "object",
    "received": "string",
    "path": [],
    "message": "Expected object, received string"
  }
]]

```

cc @IdoPesok

### CODE REVIEW

**Review by shuding — APPROVED** [review]

**Comment by IdoPesok** [comment]
@MaxLeiter 

Looking into it, is this line missing a JSON.parse() ? Because the ToolCallPayload type shows arguments as a record but seems like they never get parsed from string.

https://github.com/vercel/ai/blob/aab5324cb31514b8e95e9d722859651248f8497f/packages/core/streams/openai-stream.ts#L608

**Comment by IdoPesok** [comment]
As per the OpenAI API docs, there should be a `JSON.parse(tool.function.arguments)` I actually ran into this in a different project I was working on so I did a ` if typeof arguments === "string" ? JSON.parse(...) : ...` which should be safe. The problem is this could be a breaking change for many codebases if they have already implemented the parse themselves because then it would be a `JSON.parse(JSON.parse(...))`.

https://platform.openai.com/docs/guides/function-calling

**Comment by mharris717** [comment]
Same issue as Ido. Real bummer, as it means the main docs page example for flagship feature Generative AI straight up doesn’t work. The example only doesn’t crash cause it doesn’t care that flight number is passed as undefined.

**Comment by IdoPesok** [comment]
In #1084 I updated it so tool calls have their arguments go through `JSON.parse` then through the Zod parse. This should fix everything. Tool arguments will be able to be parsed by zod, and then the args send to the `render` function will be properly transformed according to the zod schema (enabling `.default`, `.transform`, etc)

**Comment by nicholasraphael** [comment]
this is happening again followed the example from here exactly https://sdk.vercel.ai/docs/concepts/ai-rsc @MaxLeiter @shuding

**Pull request merged**
