### PR TITLE
Fix for #637

### PR DESCRIPTION
**Pull request by peterdresslar**
Syncs libraries back up. According to my testing, the mismatched `CompletionChoice` interfaces was a problem for TypeScript agreement.

Added in the CompletionUsage interface since it could be helpful at some point.

### CODE REVIEW

**Comment by MaxLeiter** [comment]
Thanks @peterdresslar! I can't contribute as a maintainer to your `main` branch; would you mind adding a changeset? 

`pnpm changeset add` from the root, hit enter twice until it asks for patch notes, then write your changelog message and commit the file added to `.changeset`.

**Comment by peterdresslar** [comment]
Sorry about that @MaxLeiter , new to `changeset`

**Comment by MaxLeiter** [comment]
my bad -- can you edit the changeset to only have 
```
'ai': patch
```
instead of all the other projects?

thanks!

**Comment by peterdresslar** [comment]
Ah shoot, I had a feeling about that. Anyway, hopefully that works

**Review by MaxLeiter — APPROVED** [review]

**Pull request merged**
