### PR TITLE
updated body to also accept a function

### PR DESCRIPTION
**Pull request by cosbgn**
Updated body and options.body to also accept a function. (This is my first PR ever, please let me know if I'm doing something wrong!)

### CODE REVIEW

**Comment by cowboycodr** [comment]
Can someone take a look at this? This functionality is very vital and should be prioritized immediately.

**Comment by MaxLeiter** [comment]
Sorry @cosbgn, I've been busy and left this.

Copying from another PR because I noticed some docs were missing:

> I noticed that the ability to pass a custom body/headers via complete and append was missing from the docs and just added it. Would that cover your use case here?

**Comment by about-hector** [comment]
please get this done asap 🥲 
it's frustrating and counterintuitive the way it works now.

it's been a month

**Comment by lgrammel** [comment]
For React, you can now fully control the body that is sent to the server: https://sdk.vercel.ai/examples/next-pages/chat/use-chat-custom-body

**Pull request closed without merging**
