### PR TITLE
structured outputs draft

### PR DESCRIPTION
**Pull request by BrianHung**
Kinda tricky to implement `response_format` and `strict: true` as they are OpenAI specific, while `generateObject` and `genericText` are generic to the model.

```ts
import { openai } from '@ai-sdk/openai';
import { generateObject } from 'ai';
import { z } from 'zod';
import zodToJsonSchema from 'zod-to-json-schema';

const schema = z.object({
  recipe: z.object({
    name: z.string(),
    ingredients: z.array(z.string()),
    steps: z.array(z.string()),
  }),
})

const response_format = { 
  type: 'json_schema',
 'json_schema': {
    name: 'lasagna recipe',
    description: 'Generate a lasagna recipe.',
    strict: true,
    schema: zodToJsonSchema(schema)
  }
}

const { object } = await generateObject({
  model: openai('gpt-4-turbo', { response_format }),
  schema,
  prompt: 'Generate a lasagna recipe.',
});

console.log(JSON.stringify(object, null, 2));
```

### CODE REVIEW

**Comment by lgrammel** [comment]
@BrianHung my idea was to fully encapsulate this in the openai provider. it should be set automatically when applicable (if a special flag on the provider is set)

**Comment by lgrammel** [comment]
@BrianHung there is an ask that i need to get this shipped asap today, so i might open a conflicting pr

**Comment by BrianHung** [comment]
An alternative API sketch could be the following, but would require more careful TypeScript.

```ts
const { object } = await generateObject({
  model: openai('gpt-4-turbo'),
  mode: 'json_schema', // supported modes is inferred from the model
  json_schema: { // json_schema or schema & prompt fields are inferred from the mode
    name: 'lasagna recipe',
    description: 'Generate a lasagna recipe.',
    strict: true,
    schema: z.object({
      recipe: z.object({
        name: z.string(),
        ingredients: z.array(z.string()),
        steps: z.array(z.string()),
      }),
    })
  },
});
```

**Comment by BrianHung** [comment]
@lgrammel no worries! I just felt like sketching this out because I was curious to how `generateText` and `generateObject` work

**Comment by lgrammel** [comment]
WIP: https://github.com/vercel/ai/pull/2582

**Pull request closed without merging**
