### PR TITLE
feat: add vue composables and nuxt implementation

### LINKED ISSUE #77: Vue integration
I'd be very happy to pitch in to add a Vue integration (and perhaps a Nuxt one too) if you are interested 😊

We could use a utility like https://github.com/Kong/swrv to ensure implementation details are largely similar across libraries.

### PR DESCRIPTION
**Pull request by danielroe**
resolves #77

### CODE REVIEW

**Review by MaxLeiter — CHANGES_REQUESTED** [review]

**Comment by shuding** [comment]
Thank you! It would be nice to add a changeset too and we’ll do a new release!

**Comment by shuding** [comment]
Getting this, could you regenerate the lockfile?

> ERR_PNPM_OUTDATED_LOCKFILE  Cannot install with "frozen-lockfile" because pnpm-lock.yaml is not up to date with examples/nuxt-openai/package.json

**Comment by danielroe** [comment]
Sorry about that!

**Comment by shuding** [comment]
Thanks a lot!

**Comment by Justineo** [comment]
I think the repo description on GitHub should also be updated 😄

**Comment by dosstx** [comment]
Thanks! Now I have a reason to move to Vercel vs Netlify....

**Pull request merged**
