### PR TITLE
feat (provider/bedrock): add titan embedding support

### PR DESCRIPTION
**Pull request by gastonfartek**
This PR adds _basic_  support for Bedrock's `amazon.titan-embed-text-v1` and `amazon.titan-embed-text-v2:0` embeddings

### CODE REVIEW

**Comment by lgrammel** [comment]
Awesome! Can you add a changeset, examples, and update the docs?

**Comment by gastonfartek** [comment]
@lgrammel done! lmk if I missed anything

**Comment by VaggelisKa** [comment]
Would be willing to give this a shot on a prerelease version or an rc.

**Review by lgrammel — APPROVED** [review]

**Review by flamfoof — COMMENTED** [review]
This is cool. I like your mocks and tests!

**Pull request merged**
