### PR TITLE
Compatibility extension of openai's compatibility mode

### PR DESCRIPTION
**Pull request by minpeter**
There are two changes here:
1. When setting `compatibility: "compatible"` in `createOpenAI`, the messages[].content field in the `chat/completions` request has been changed to strings.
2. The `object` filter has been excluded from the response value filter of `chat.completions`.

Related issues: #1754 

This patch verifies that the examples provided through the FriendliAI endpoint work well.

And I'm not sure, but fireworks ai also didn't work before this patch, but after the patch it returns a response successfully.

Perhaps this patch will have a positive effect on the behavior of many other companies besides groq and Perplexity. 👍🏼

### CODE REVIEW

**Review by lgrammel — CHANGES_REQUESTED** [review]
This removes the image parts in compatible mode and is a breaking change.

**Comment by minpeter** [comment]
Would it be okay if I changed the logic to modify it to send a string if there are no image fields and it is in compatible mode?

**Comment by minpeter** [comment]
I think it’s a good idea.

I‘ll post the correction when I get home.

**Comment by minpeter** [comment]
I forgot to delete unused parameters.

**Comment by lgrammel** [comment]
@minpeter thanks, this looks good. I'll take it from here, need to add tests & changeset so I'll continue in a separate PR

**Comment by minpeter** [comment]
Question in a different context: Is there a business process that must be followed to add a provider to the AI ​​SDK document?

**Comment by lgrammel** [comment]
> Question in a different context: Is there a business process that must be followed to add a provider to the AI ​​SDK document?

If you mean 3rd party providers, it depends. We will probably maintain the ones for the big cloud providers and large LLM providers in our repo (e.g. Bedrock, Azure OpenAI). For other providers you can publish them as community providers in your own repo and we are more than happy to list them under community providers, see https://sdk.vercel.ai/providers/community-providers

**Comment by minpeter** [comment]
> > Question in a different context: Is there a business process that must be followed to add a provider to the AI ​​SDK document?
> 
> If you mean 3rd party providers, it depends. We will probably maintain the ones for the big cloud providers and large LLM providers in our repo (e.g. Bedrock, Azure OpenAI). For other providers you can publish them as community providers in your own repo and we are more than happy to list them under community providers, see https://sdk.vercel.ai/providers/community-providers

thanks :)

**Comment by lgrammel** [comment]
Superseeded by https://github.com/vercel/ai/pull/1765

**Pull request closed without merging**
