### PR TITLE
Update openai-functions.mdx

### PR DESCRIPTION
**Pull request by mengxi-ream**
openai change its type name and location in "openai": "^4.10.0",

### CODE REVIEW

**Comment by MaxLeiter** [comment]
Thanks for this! Would you mind updating `openai` in the examples and the types being used there as well?

**Comment by Crayon-ShinChan** [comment]
> Thanks for this! Would you mind updating `openai` in the examples and the types being used there as well?

sorry, do you mean types used in `https://sdk.vercel.ai/docs/guides/providers/openai`? But I didn't find any imported types from openai in that page

**Comment by peterdresslar** [comment]
Is `ChatCompletionCreateParams` really required for this example? The [OpenAI example at the API docs](https://platform.openai.com/docs/guides/gpt/function-calling) just defines `functions` as a plain array. This works fine when plugged into the completion constructor in the documented AI SDK example.

This could also be a chance to opportunistically update the model name in the documentation also to just plain 'gpt-3.5-turbo'

**Comment by Crayon-ShinChan** [comment]
> Is `ChatCompletionCreateParams` really required for this example? The [OpenAI example at the API docs](https://platform.openai.com/docs/guides/gpt/function-calling) just defines `functions` as a plain array. This works fine when plugged into the completion constructor in the documented AI SDK example.
> 
> 
> 
> This could also be a chance to opportunistically update the model name in the documentation also to just plain 'gpt-3.5-turbo'

I think it's not necessary just for type safety~

**Comment by lgrammel** [comment]
We have changed to a new docs system. Please re-open if this is still an issue with the new docs.

**Pull request closed without merging**
