### PR TITLE
add: useChat dynamic body option via function in svelte

### PR DESCRIPTION
**Pull request by cowboycodr**
Add support for dynamic body option via function in Svelte.

Example:
```svelte
<script>
     ...
     function getBody() {
          return {};
     }

     let chat = useChat({..., body: getBody})
</script>
```

### CODE REVIEW

**Comment by MaxLeiter** [comment]
Thanks for the PR @cowboycodr, sorry for missing this. 
I noticed that the ability to pass a custom `body`/`headers` via `complete` and `append` was missing from the docs and just added it. Would that cover your use case here?

**Comment by cowboycodr** [comment]
Yes. Thank you!

**Comment by MaxLeiter** [comment]
https://github.com/vercel/ai/commit/d05a146d19ddfe6736a3a65ed29930d959fd139f

**Comment by cowboycodr** [comment]
@MaxLeiter maybe I'm using the `append` function incorrectly, however, the chatOptions object is never making it to the server side
+page.svelte
image
+server.js
image
console
image

**Pull request closed without merging**
