### PR TITLE
feat (@ai-sdk/azure): add azure openai completion support 

### PR DESCRIPTION
**Pull request by lgrammel**
## Summary
Adds support for OpenAI completion models (`gpt-3.5-turbo-instruct`) to the Azure OpenAI provider.

## Tasks

- [x] example: test streaming
- [x] test: regression openai completion
- [x] test: azure completion
- [x] docs: provider page
- [x] changeset

### CODE REVIEW

**Comment by lgrammel** [comment]
@Und3rf10w can you test the `examples/ai-core/src/stream-text/azure-completion.ts` manually (`pnpm tsx src/stream-text/azure-completion`) with your azure completion deployment and confirm it works? I don't have a completion deployment available for testing

**Comment by Und3rf10w** [comment]
> @Und3rf10w can you test the `examples/ai-core/src/stream-text/azure-completion.ts` manually (`pnpm tsx src/stream-text/azure-completion`) with your azure completion deployment and confirm it works? I don't have a completion deployment available for testing


@lgrammel , I tested this fork with:

```typescript
import { createAzure } from '../../../../packages/azure/src/azure-openai-provider';
import { streamText } from 'ai';
import dotenv from 'dotenv';

dotenv.config();

async function main() {
  const azure = createAzure({
    resourceName: '<redacted>',
    apiKey: '<redacted>',
  })

  const result = await streamText({model: azure.completion('gpt-35-turbo-instruct'),
    prompt: 'Invent a new holiday and describe its traditions.',
  });

  for await (const textPart of result.textStream) {
    process.stdout.write(textPart);
  }
}

main().catch(console.error);
```

And got:

```
TypeError: Failed to parse URL from undefined/completions
    at node:internal/deps/undici/undici:12500:13
    at async postToApi (ai-sdk/node_modules/.pnpm/@ai-sdk+provider-utils@0.0.14_zod@3.23.8/node_modules/@ai-sdk/provider-utils/dist/index.js:351:22) {
  [cause]: TypeError: Invalid URL
      at new URL (node:internal/url:804:36)
      at new Request (node:internal/deps/undici/undici:4839:25)
      at fetch (node:internal/deps/undici/undici:9651:25)
      at fetch (node:internal/deps/undici/undici:12498:10)
      at fetch (node:internal/bootstrap/web/exposed-window-or-worker:79:16)
      at postToApi (ai-sdk/node_modules/.pnpm/@ai-sdk+provider-utils@0.0.14_zod@3.23.8/node_modules/@ai-sdk/provider-utils/dist/index.js:351:28)
      at postJsonToApi (ai-sdk/node_modules/.pnpm/@ai-sdk+provider-utils@0.0.14_zod@3.23.8/node_modules/@ai-sdk/provider-utils/dist/index.js:323:7)
      at OpenAICompletionLanguageModel.doStream (ai-sdk/node_modules/.pnpm/@ai-sdk+openai@0.0.29_zod@3.23.8/node_modules/@ai-sdk/openai/internal/dist/index.js:789:97)
      at ai-sdk/node_modules/.pnpm/ai@3.1.36_openai@4.47.1_react@18.2.0_solid-js@1.8.7_svelte@4.2.3_vue@3.3.8_typescript@5.1.3__zod@3.23.8/node_modules/ai/dist/index.js:1767:17
      at _retryWithExponentialBackoff (ai-sdk/node_modules/.pnpm/ai@3.1.36_openai@4.47.1_react@18.2.0_solid-js@1.8.7_svelte@4.2.3_vue@3.3.8_typescript@5.1.3__zod@3.23.8/node_modules/ai/dist/index.js:139:18) {
    code: 'ERR_INVALID_URL',
    input: 'undefined/completions'
  }
}
```

As well as:

```typescript
import { azure } from '../../../../packages/azure/src/azure-openai-provider';
import { streamText } from 'ai';
import dotenv from 'dotenv';

dotenv.config();

async function main() {
  const azureProvider = azure({
    apiKey: '<redacted>',
    resourceName: '<redacted>',
  });
  const result = await streamText({
    model: azure.completion('gpt-35-turbo-instruct'), // use your own deployment
    prompt: 'Invent a new holiday and describe its traditions.',
  });

  for await (const textPart of result.textStream) {
    process.stdout.write(textPart);
  }
}

main().catch(console.error);
```

That one thinks the api key is missing.

I think there might be a problem with the constructor, but entirely possible I'm doing something wrong.

**Comment by lgrammel** [comment]
@Und3rf10w can you test it as follows:

1. check out `main`
1. check out the PR via `gh pr checkout 1988`
1. run `pnpm install` in the root
1. run `pnpm build` in the root
1. `cd examples/ai-core`
1. modify the example `src/stream-text/azure-completion.ts` to have your settings (or configure the `.env` file)
1. run `pnpm tsx src/stream-text/azure-completion.ts`

This is the best way to test this out. I believe the error you are seeing might be related to package resolution issues.

**Comment by lgrammel** [comment]
Awesome, glad to see it working. The last snippet mixes the provider and the provider incorrectly. Please try:

```ts
import { createAzure } from '@ai-sdk/azure';
import { streamText } from 'ai';
import dotenv from 'dotenv';

dotenv.config();

// create provider instance via factory
const azure = createAzure({
      resourceName: '<redacted>',
      apiKey: '<redacted>',
    })
    
async function main() {
  const result = await streamText({
    model: azure.completion("gpt-35-turbo-instruct"), 
    prompt: 'Invent a new holiday and describe its traditions.',
  });

  for await (const textPart of result.textStream) {
    process.stdout.write(textPart);
  }
}

main().catch(console.error);
```

**Comment by Und3rf10w** [comment]
@lgrammel: That snippet worked with a response:

```
"Community Appreciation Day" is a holiday that celebrates the importance of community
```

**Review by nicoalbanese — APPROVED** [review]

**Pull request merged**
