### PR TITLE
feat (ai/swarm): basic non-streaming experimental swarm implementation

### PR DESCRIPTION
**Pull request by lgrammel**
## Summary
- introduce `@ai-sdk/swarm`
- add basic swarm example
- implementation limited to non-streaming `runSwarm`

### CODE REVIEW

**Comment by lgrammel** [comment]
@numman-ali thanks - this is super early and experimental, will probably release it incrementally (please note that this package is for exploration, we might not maintain it at all).

**Review by jeremyphilemon — APPROVED** [review]

**Comment by RobertHH-IS** [comment]
Awesome! Lets get this into main under experimental!

**Comment by BrentFarese** [comment]
What is the status of this work?  Saw some code pushed in swarm package but then pulled out of the SDK?  We are running multiple agents using tools and Vercel AI SDK.  Running into some complexity of agent handoff and more.  Thanks!

**Comment by lgrammel** [comment]
@BrentFarese removed - there are some open source swarm-like packages that build on the ai sdk

**Comment by BrentFarese** [comment]
> @BrentFarese removed - there are some open source swarm-like packages that build on the ai sdk

Thanks @lgrammel!  Are there any plans at Vercel to do multi-agent orchestration in some form?  Tool calling is awesome but once you start creating multiple inter-connected agents, you start hitting some walls.

**Comment by ekremkenter** [comment]
So you removed it yesterday @lgrammel? I see a new version of that dated 4 days ago 
https://www.npmjs.com/package/@ai-sdk/swarm?activeTab=readme

**Comment by ItayElgazar** [comment]
> @BrentFarese removed - there are some open source swarm-like packages that build on the ai sdk

Do you have a name? I tried finding but couldn't find any

**Comment by lgrammel** [comment]
> > @BrentFarese removed - there are some open source swarm-like packages that build on the ai sdk
> 
> Do you have a name? I tried finding but couldn't find any

There is e.g. https://github.com/K-Mistele/swarm

**Pull request merged**
