### PR TITLE
Vue use assistant

### PR DESCRIPTION
**Pull request by dosstx**

### CODE REVIEW

**Comment by dosstx** [comment]
@danielroe and @lgrammel : I am at a loss on how to proceed. Trying to get this update into the library but I keep stumbling. Anyone able to take it from here?

**Comment by lgrammel** [comment]
@dosstx I'll work on integrating it this week

**Comment by dosstx** [comment]
> @dosstx I'll work on integrating it this week

Thank you, I really appreciate it. I'll try and help with docs.

**Comment by lgrammel** [comment]
I gave it a look today. The pattern is different from the implementation in `vue/use-chat.ts`, where we use `useSWRV`. I'm not familiar with `reactive`. My suggestion would be to change it to be similar with use-chat, i.e., use `useSWRV`. I suspect that this is the cause of the `Type instantiation is excessively deep and possibly infinite.` error, but haven't looked into the details.

Also, please add `UseAssistantHelpers` similar to `react/use-assistant.ts`

**Comment by dosstx** [comment]
@danielroe Two questions:

1. Should we be using `swrv` in this assistant composable?

2. To fix the excessively deep type issue, should I replace `reactive` with `ref` in this case?

```
const state = reactive({
    messages: [] as Message[],
    input: '',
    threadId: undefined as string | undefined,
    status: 'awaiting_message' as AssistantStatus,
    error: undefined as unknown,
  });
  ```

**Comment by lgrammel** [comment]
We ended up with this implementation: https://github.com/vercel/ai/pull/2245

**Pull request closed without merging**
