### PR TITLE
fix(docs): replace `vue` with `svelte` in SvelteKit guide

### PR DESCRIPTION
**Pull request by justindomingue**

### CODE REVIEW

**Review by justindomingue — COMMENTED** [review]
replace one more instance of vue

**Review by justindomingue — COMMENTED** [review]
replace one more instance of vue

**Review by justindomingue — COMMENTED** [review]
replace one more instsance

**Review by MaxLeiter — APPROVED** [review]

**Review by MaxLeiter — APPROVED** [review]

**Comment by MaxLeiter** [comment]
Thank you!

**Pull request merged**
