### PR TITLE
fix: types for onChange event on input/textarea on react lib added

### PR DESCRIPTION
**Pull request by stylessh**
Types for onChange event added on react useChat and useCompletion lib.

Before:
```ts
/** An input/textarea-ready onChange handler to control the value of the input */
  handleInputChange: (e: any) => void
```

After:
```ts
/** An input/textarea-ready onChange handler to control the value of the input */
  handleInputChange: (e: React.ChangeEvent<HTMLInputElement> | React.ChangeEvent<HTMLTextAreaElement>) => void
```

### CODE REVIEW

**Comment by stylessh** [comment]
When I run prettier-fix it changes a lot of untouched files

**Comment by MaxLeiter** [comment]
@stylessh be sure you've updated your branch with the recent commits from `main`

**Comment by stylessh** [comment]
@MaxLeiter done

**Comment by stylessh** [comment]
I'm not sure why's prettier check not working, I runned prettier fix and nothing 😓

**Pull request merged**
