### PR TITLE
feat (docs): Add AnthropicVertex community provider

### PR DESCRIPTION
**Pull request by nalaso**
Added AnthropicVertex Provider to community providers list

### CODE REVIEW

**Comment by fry69** [comment]
This implementation is still broken, it has the same issues I described in my review comments, see here -> https://github.com/vercel/ai/pull/2482

**Comment by nalaso** [comment]
1. The extra / was because I was passing it after the base URL. this.path still remains the same.
2. anthropicVertex works if you pass the correct variables to the env.

**Comment by fry69** [comment]
It should work without setting environment variables and not produce an error. This is a clear bug.

**Comment by nalaso** [comment]
Let me check.

**Review by lgrammel — APPROVED** [review]

**Comment by fry69** [comment]
Also streaming does not seem to work, no output from this code ->
```ts
import { createAnthropicVertex } from 'anthropic-vertex-ai';
import { generateText, streamText } from 'ai';

const vertexProvider = createAnthropicVertex({
  region: 'europe-west1',
  projectId: 'my-id-1234',
});

const vertexHaiku = vertexProvider('claude-3-haiku@20240307');

const { textStream } = await streamText({
  model: vertexHaiku,
  prompt: 'Write a long poem about embedding models.',
});

for await (const textPart of textStream) {
  console.log(textPart);
}
```

**Comment by lgrammel** [comment]
Please run `pnpm prettier-fix`

**Comment by nalaso** [comment]
All the issues has been fixed now @fry69 @lgrammel 

https://github.com/nalaso/anthropic-vertex-ai

**Pull request merged**
